# use this environment file to build the environment
# on MacOS OSX machines; tested on osx-64 Mojave
# 10.14.5 Darwin kernel with latest Anaconda
# from https://repo.anaconda.com/archive/Anaconda3-2019.07-MacOSX-x86_64.sh
---
name: esmvaltool
channels:
  - conda-forge

dependencies:
  # Python packages that cannot be installed from PyPI:
  - xarray>=0.12.0  # Can be installed from PyPI, but here to get a consistent set of depencies with iris.
  # Non-Python dependencies
  - cdo
  - imagemagick
  - nco

  # Multi language support:
  - tiledb=1.6.0  # Needed by the new ncl=6.6.2; conda keeps it at 1.2.2
  - ncl
  - r-base
  - r-curl  # Dependency of lintr, but fails to compile because it cannot find libcurl installed from conda.
  - r-udunits2  # Fails to compile because it cannot find udunits2 installed from conda.
